name: Daily Backtest

on:
  schedule:
    # 毎日06:30に実行（JST時間、UTC時間は21:30前日）
    # データ取得の30分後に実行
    - cron: '30 21 * * *'
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'main_parallel.py'
      - 'backtest_engine.py'
      - 'report_generator.py'
      - 'config.py'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  backtest:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        # キャッシュディレクトリも含めてチェックアウト
        fetch-depth: 0
        # プッシュ権限を有効化
        token: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create directories
      run: |
        mkdir -p cache
        mkdir -p logs
        mkdir -p results
        mkdir -p reports
        
    - name: Run cache-only backtest
      run: |
        python main_parallel.py --cache-only --num-runs 3 --base-seed 42
        
    - name: Commit and push results
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # バックテストで生成されたファイルを一旦ステージング（修正版）
        git add reports/
        git add -f logs/
        git add -f results/
        
        # 未ステージの変更をコミット（一時的）
        if ! git diff --staged --quiet; then
          git commit -m "Temporary commit for rebase"
        fi
        
        # 最新の変更を取得
        git pull --rebase
        
        # レポート、ログ、結果を再度追加
        git add reports/
        git add -f logs/
        git add -f results/
        
        # 変更がある場合のみコミット
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Daily backtest results $(TZ='Asia/Tokyo' date +'%Y-%m-%d %H:%M:%S JST')"
          git push
        fi