name: 自動バックテスト実行

on:
  schedule:
    # 毎日朝6時に実行（日本時間）
    - cron: '0 6 * * *'
  workflow_dispatch:  # 手動実行も可能

jobs:
  backtest:
    runs-on: ubuntu-latest
    
    steps:
    - name: リポジトリのチェックアウト
      uses: actions/checkout@v3
    
    - name: Python 3.9のセットアップ
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: 依存関係のインストール
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: バックテスト実行
      run: |
        python main.py --start-date 2023-01-01 --end-date $(date +%Y-%m-%d)
    
    - name: レポートファイルのアップロード
      uses: actions/upload-artifact@v3
      with:
        name: backtest-reports
        path: reports/
        retention-days: 30
    
    - name: GitHub Pagesへのデプロイ
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./reports
        force_orphan: true
