name: Daily Backtest

on:
  schedule:
    # 毎日06:00に実行（UTC時間、日本時間は15:00）
    - cron: '0 6 * * *'
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  backtest:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        # キャッシュディレクトリも含めてチェックアウト
        fetch-depth: 0
        # プッシュ権限を有効化
        token: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create cache directory
      run: |
        mkdir -p cache
        mkdir -p logs
        mkdir -p results
        
    - name: Run backtest
      run: |
        python main.py --num-runs 3 --base-seed 42
        
    - name: Commit and push results
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # キャッシュファイル、レポート、ログを強制的に追加（.gitignoreを無視）
        git add -f cache/
        git add reports/
        git add -f logs/
        git add -f results/
        
        # 変更がある場合のみコミット
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Daily backtest results and cache update $(date +'%Y-%m-%d %H:%M:%S')"
          git push
        fi
