name: Create Initial Seeds

on:
  workflow_dispatch:
    inputs:
      num_seeds:
        description: '作成するシード値の数'
        required: false
        default: '10'
        type: string

permissions:
  contents: write

jobs:
  create-seeds:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create directories
      run: |
        mkdir -p cache
        mkdir -p logs
        mkdir -p results
        mkdir -p reports
        
    - name: Create initial seed mappings
      run: |
        NUM_SEEDS="${{ github.event.inputs.num_seeds || '10' }}"
        echo "初期シード値マッピングを作成します: $NUM_SEEDS個"
        python main_parallel.py --create-seeds
        
    - name: Commit and push seed mappings
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # 生成されたファイルの状態を確認
        git status
        
        # シード値マッピングファイルが作成されているかチェック
        if [ -f "seed_mapping.json" ]; then
          echo "シード値マッピングファイルが見つかりました"
          git add seed_mapping.json
          git add -f logs/
          
          # 未ステージの変更があるかチェック
          if ! git diff --quiet || ! git diff --cached --quiet; then
            # 変更があれば一時的にステージングしてコミット
            git commit -m "Temporary commit for rebase"
          fi
          
          # 最新の変更を取得
          git pull --rebase
          
          # シード値マッピングファイルを最終コミット用にステージング
          git add seed_mapping.json
          git add -f logs/
          
          # 最終コミット（必ず実行）
          git commit --amend -m "Create initial seed mappings $(TZ='Asia/Tokyo' date +'%Y-%m-%d %H:%M:%S JST')"
          git push --force-with-lease
        else
          echo "シード値マッピングファイルが見つかりません"
          exit 1
        fi
