name: Daily Data Fetch

on:
  schedule:
    # 毎日06:00に実行（JST時間、UTC時間は21:00前日）
    - cron: '0 21 * * *'
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'data_fetcher.py'
      - 'data_loader.py'
      - 'config.py'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  data-fetch:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        # キャッシュディレクトリも含めてチェックアウト
        fetch-depth: 0
        # プッシュ権限を有効化
        token: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create cache directory
      run: |
        mkdir -p cache
        mkdir -p logs
        mkdir -p results
        
    - name: Run data fetch only
      run: |
        python main_parallel.py --data-only --all-stocks
        
    - name: Commit and push cache updates
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # 生成されたファイルの状態を確認
        git status
        
        # 未ステージの変更があるかチェック
        if ! git diff --quiet || ! git diff --cached --quiet; then
          # 変更があれば一時的にステージングしてコミット
          git add -f cache/
          git add -f logs/
          git commit -m "Temporary commit for rebase"
        fi
        
        # 最新の変更を取得
        git pull --rebase
        
        # データ取得で生成されたファイルを最終コミット用にステージング
        git add -f cache/
        git add -f logs/
        
        # 最終コミット（必ず実行）
        git commit --amend -m "Daily data fetch and cache update $(TZ='Asia/Tokyo' date +'%Y-%m-%d %H:%M:%S JST')"
        git push --force-with-lease
